language: java
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
notifications:
  slack:
    secure: iMxF0nbMV4dXrZ4wFV4M7o97bioMygH6sRdjPv9D4ZG3G/6lata2mPd2gO3vzpzNAF4QAUqkBm8z/1XeIAmfQh/T3S1JRgQ+qqwwE/LC6okgpjt80AiEjTNJXJcAvXAbJ//Jv8NXAINr4HhID4AmT+LtY7q9d03QxhXY6Ypqiw/UVVYUWARH6cl5oHQfmPZ3g5y9C52HGm6IffgIw9jX02QdWFfNMhdKBXtZppUl8O3vWbU9Y0MbZO31YXGH0VuDMj5LoC7kIFgpuoEAjGNE9IMKmn2B5o8FJNKgH7lqR6gj3RecX/f+JgxJBQl1yusAuzdu6fpDufiR+WeSEptLYZB8ifb8PMyvo+MfOjdl8KQxO1HacULPJ9he8CFkaSlmmAUxl9fGjIbYtV4HWu7vvlcyLZVVH/8fq5JMdI0PClFXksRvKqy0VlcjchxD1U5fJaixYOMIOxM+84xM6YWayTGz6Ze5Po9CoGxPC3P0k7b76smcqWyiC659GIC12Pk+38DODBGst++mt7jCmhJEHe6JBi3IWWtjqoxd9pYB0BvW9yiCLFWpjBSGDhaqz4BZ77gveK97DAR0kMjXMvBKc+rBaXIzNtq5/lMiILXpkpTomx+BVoeY8DV9Hvi4ZIge7dWv/5uclYD1QJm8+QCG5XPIyxdhc0mGDGFb6FDRBBI=
